// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uryljfmbzthbgiqsqmjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyeWxqZm1ienRoYmdpcXNxbWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NDAzMjcsImV4cCI6MjA1ODMxNjMyN30.mUj1v08qWhcn9iA_C1xdMbaVZrzGDwO-oRBoEsdj9Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);